#docker-compose-proxy.yml

version: '3.8'

services:
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - maple_network

networks:
  maple_network:
    name: maple_network
    external: true