# ./docker-compose.yml

services:
  nginx:
    image: ${DOCKER_USERNAME}/maple-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - maple_network

  backend:
    image: ${DOCKER_USERNAME}/maple-backend:latest
    restart: always
    env_file:
      - ./.env
    networks:
      - maple_network

networks:
  maple_network:
    external: true
    name: maple_network
