# ./docker-compose.yml

services:
  nginx:
    image: ${{ secrets.DOCKER_USERNAME }}/maple-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - maple_network

  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/maple-backend:latest
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      FRONTEND_REDIRECT_URL: ${FRONTEND_REDIRECT_URL}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    networks:
      - maple_network

networks:
  maple_network:
    external: true
    name: maple_network
