# ./docker-compose.yml

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - maple_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
    networks:
      - maple_network

networks:
  maple_network:
    external: true
    name: maple_network
